## Основы numpy

Давайте знакомиться с библиотекой NumPy (Numeric Python)! 

Это библиотека Python с открытым исходным кодом, которая активно используется во многих технических областях, в том числе - в машинном обучении. Numpy можно назвать стандартом для работы с числовыми данными в Python, его API широко используется в пакетах Pandas, SciPy, Matplotlib, scikit-learn, scikit-image и в большинстве других научных пакетов Python. Библиотека вводит полезный тип данных с названием ndarray, о котором можно думать как о n-мерной матрице, и методы для эффективной работы с ним. NumPy может использоваться для выполнения множества математических операций над такими массивами, чем мы впоследствии будем пользоваться при реализации нейронных сетей и генеративных моделей.

In [1]:
# установим библиотеку
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
# импортируем её
import numpy as np

### Array (ndarray)

Главный объект numpy - array. N-мерные массивы схожи со списками в python, но элементы массива должны иметь одинаковый тип данных. С массивами можно проводить числовые операции с большим объемом информации в разы быстрее и, главное, намного эффективнее чем со списками.

In [3]:
a = np.array([1, 2, 3, 4, 5])
print(a, '|', type(a))

[1 2 3 4 5] | <class 'numpy.ndarray'>


In [4]:
a.dtype

dtype('int64')

### Срезы

Очень важно уметь манипулировать элементами массива. Наверное, использование срезов это одна из наиболее частых операций при работе с данными, и c ndarray они работают также как и с питоновскими списками:

In [5]:
a[:2]

array([1, 2])

In [6]:
a[::2]

array([1, 3, 5])

Многомерный массив является центральной структурой данных библиотеки NumPy. Все элементы имеют одинаковый тип, хранимый в dtype. Ранг массива - это число измерений. Форма массива представляет собой набор целых чисел, дающих размер массива по каждому измерению.

In [7]:
a = np.array([[1, 2, 3], [4, 5, 6]], float)
print(a, '|', type(a))

[[1. 2. 3.]
 [4. 5. 6.]] | <class 'numpy.ndarray'>


Мы можем получить доступ к элементам в массиве, используя квадратные скобки. Когда вы обращаетесь к элементам, помните, что индексирование в NumPy начинается с 0. 

In [8]:
a[0]

array([1., 2., 3.])

In [9]:
a[1,2]

6.0

Срезы в многомерных массивах работают аналогично с одномерными, и каждый срез применяется как фильтр для установленного измерения. Используйте ":" в измерении для указывания использования всех элементов этого измерения:

In [10]:
a = np.array([[1, 2, 3], [4, 5, 6]], float)
# выбрали элементы с шагом 2 второй строки массива
a[1,::2]

array([4., 6.])

У массива может быть разное количество измерений: 1-D массиву соответствует вектор (причем это может бытькак вектор-строка, так и вектор-столбец), 2-D массиву - двумерная матрица. Для трехмерных или более крупных размерных массивов также обычно используется термин тензор.

In [11]:
a

array([[1., 2., 3.],
       [4., 5., 6.]])

Метод shape возвращает количество строк и столбцов в матрице:

In [12]:
a.shape

(2, 3)

### Создание массива

Чтобы создать простой массив ndarray, можно просто передать ему список. При желании вы также можете указать тип данных в вашем списке. О типах данных можно почитать [здесь](https://numpy.org/devdocs/reference/arrays.dtypes.html#arrays-dtypes).

Помимо создания массива из последовательности элементов, вы можете легко создать массив, заполненный нулями:

In [13]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Или массив, заполненный 1:

In [14]:
np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

Или даже пустой массив! Функция empty создает массив, исходное содержимое которого является случайным и зависит от состояния памяти. Причиной использования пустых над нулями (или чего-то подобного) является скорость - просто убедитесь, что впоследствии не забыли заполнить массив не-мусорными данными!

In [15]:
np.empty(4)

array([5.e-324, 5.e-324, 5.e-324, 0.e+000])

Можно создать массив с диапазоном элементов:

In [16]:
np.arange(4)

array([0, 1, 2, 3])

И даже массив, который содержит диапазон равномерно распределенных интервалов. Для этого вам необходимо указать первое число, последнее число и размер шага.

In [17]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

Вы также можете использовать np.linspace() для создания массива со значениями, которые расположены линейно с заданным интервалом:

In [18]:
# от 0 до 10, 5 чисел с равным шагом
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

float64, это числовой тип данных в numpy, который используется для хранения вещественных чисел двойной точности по аналогии с float в Python.

Метод dtype возвращает тип переменных, хранящихся в массиве:

In [19]:
a.dtype

dtype('float64')

Хотя тип данных по умолчанию - с плавающей запятой (np.float64), вы можете явно указать, какой тип данных вы хотите, используя ключевое слово dtype.

In [20]:
x = np.ones(2, dtype=np.int64)
x

array([1, 1])

### Добавление, удаление и сортировка элементов

Сортировать элементы можно с помощью np.sort() (кому интересно, по умолчанию используется алгоритм timsort). Вы можете указать ось, вид и порядок при вызове функции.

In [21]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
# Вы можете быстро отсортировать числа в порядке возрастания с помощью:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

В дополнение к sort, который возвращает отсортированную копию массива, вы можете использовать:

* argsort, который является косвенной сортировкой вдоль указанной оси,

* lexsort, который является косвенной стабильной сортировкой по нескольким ключам,

* searchsorted, который найдет элементы в отсортированном массиве, и

* partition, который является частичной сортировкой.

Все надстройки смотрите [тут](https://numpy.org/devdocs/reference/generated/numpy.sort.html#numpy.sort)

Чтобы удалить элементы из массива, просто использовать индексирование для выбора элементов, которые вы хотите сохранить.

In [22]:
a = np.array([1, 2, 3])
# берем элементы на первом и 2 индексе
a = a[[1, 2]]
a

array([2, 3])

### Форма и размер массива

In [23]:
a = np.array([[1, 2, 3], [4, 5, 6]], float)

Метод len возвращает длину первого измерения (оси):

In [24]:
len(a)

2

По аналогии с list можно проверять вхождение элемента.

In [25]:
6 in a

True

In [26]:
6 in a[0]

False

Чтобы узнать количество измерений массива, запустите:

In [27]:
a.ndim

2

Чтобы найти общее количество элементов в массиве, запустите:

In [28]:
a.size

6

И чтобы найти форму вашего массива, запустите:

In [29]:
a.shape

(2, 3)

In [30]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [31]:
array_example.ndim

3

In [32]:
array_example.size

24

In [33]:
array_example.shape

(3, 2, 4)

### Изменение формы массива

Массивы можно переформировать при помощи метода, который задает новый многомерный массив. Следуя следующему примеру, мы переформатируем одномерный массив из 12 элементов в двумерный массив, состоящий из 4 строк и 3 столбцов:

(метод reshape создает новый массив, а не модифицирует оригинальный)

In [145]:
a = np.array(range(12), float)
a

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

Когда вы используете метод reshape, массив, который вы хотите создать, должен иметь то же количество элементов, что и исходный массив. 

In [146]:
a = a.reshape((4, 3))
a

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [147]:
# неверное количество элементов
a.reshape((13))

ValueError: ignored

In [148]:
a = np.arange(6)

In [149]:
a.reshape(3, 2)

array([[0, 1],
       [2, 3],
       [4, 5]])

Можно сделать и обратное: конвертируем в одномерный

In [39]:
a.flatten()

array([0, 1, 2, 3, 4, 5])

или чуть более общий метод:

In [150]:
a.squeeze()

array([0, 1, 2, 3, 4, 5])

### Работа по ссылке

Работа по ссылке такая же как и в python:

In [40]:
a = np.array([1, 2, 3])
b = a
c =  a.copy()

# меняем 0й элемент
a[0] = 0

print(f'Измененный массив а {a}')
print(f'Измененный массив b {b}  <-- изменился по ссылке т.к. поменяти 0й элемент а')
print(f'Измененный массив c {c}  <-- создали копию в памяти')

Измененный массив а [0 2 3]
Измененный массив b [0 2 3]  <-- изменился по ссылке т.к. поменяти 0й элемент а
Измененный массив c [1 2 3]  <-- создали копию в памяти


Можно преобразовать обратно в список:

In [41]:
a.tolist()

[0, 2, 3]

### Как преобразовать одномерный массив в двумерный массив

При написании нейронок будет ОЧЕНЬ много возни с размерностями. Каждая нейронная сеть требует на вход каждого слоя массив с вполне конкретным шейпом и часто придется данные под эти требования подгонять, добавляя дополнительные dimы.

Вы можете использовать np.newaxis или np.expand_dims для увеличения размеров вашего существующего массива. В торче для этого будет удобная функция torch.unsqueeze - об этом поговорим потом!

Использование np.newaxis увеличит размеры вашего массива на одно измерение при использовании один раз. Это означает, что одномерный массив станет 2D- массивом, 2D- массив станет 3D- массивом и так далее.

In [42]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [43]:
a

array([1, 2, 3, 4, 5, 6])

In [44]:
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [45]:
a

array([1, 2, 3, 4, 5, 6])

In [46]:
a2

array([[1, 2, 3, 4, 5, 6]])

Или, например, для вектора столбца, вы можете вставить ось вдоль второго измерения:



In [47]:
col_vector = a[:, np.newaxis]
col_vector.shape

(6, 1)

In [48]:
col_vector

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

Вы также можете расширить массив, вставив новую ось в указанной позиции с помощью np.expand_dims.

Например, если вы начинаете с этого массива:

In [151]:
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [50]:
a.shape

(6,)

In [51]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [52]:
b

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [53]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

In [54]:
c

array([[1, 2, 3, 4, 5, 6]])

Подробнее: 

[newaxis](https://numpy.org/devdocs/reference/arrays.indexing.html#arrays-indexing)
[expand_dims](https://numpy.org/devdocs/reference/generated/numpy.expand_dims.html#numpy.expand_dims)


### Объединение

Массивы можно объединять

In [55]:
a = np.array([[1, 2], [3, 4]], float)
b = np.array([[5, 6], [7,8]], float)
np.concatenate((a,b))

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.]])

Если массив не одномерный, можно задать ось, по которой будет происходить соединение. По умолчанию (не задавая значения оси), соединение будет происходить по первому измерению:

In [56]:
np.concatenate((a,b), axis=0)

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.]])

In [57]:
np.concatenate((a,b), axis=1)

array([[1., 2., 5., 6.],
       [3., 4., 7., 8.]])

Также почитайте про методы [stack](https://numpy.org/doc/stable/reference/generated/numpy.stack.html), [vstack](https://numpy.org/doc/stable/reference/generated/numpy.vstack.html), [hstack](https://numpy.org/doc/stable/reference/generated/numpy.hstack.html).

### Условное индексирование

В numpy легко выделять элементы массива, удовлетворяющие заданным условиям. Например, рассмотрим такой массив:

In [63]:
a = np.array([1 , 2, 3, 4, 5, 6, 7, 8])

In [64]:
a < 5

array([ True,  True,  True,  True, False, False, False, False])

In [65]:
a[a < 5]

array([1, 2, 3, 4])

Вы также можете выбрать, например, числа, которые равны или больше 5, и использовать это условие для индексации массива.

In [66]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [67]:
five_up = (a >= 5)
a[five_up]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

Вы можете выбрать элементы, которые делятся на 2:

In [68]:
divisible_by_2 = a[a%2==0]
divisible_by_2

array([ 2,  4,  6,  8, 10, 12])

Или вы можете выбрать элементы , которые удовлетворяют два условий с использованием & и | операторов:

In [69]:
c = a[(a > 2) & (a < 11)]
c

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [70]:
c = a[(a < 2) | (a > 11)]
c

array([ 1, 12])

Вы также можете использовать логические операторы & и | чтобы вернуть логические значения, которые указывают, соответствуют ли значения в массиве определенному условию. Это может быть полезно для массивов, которые содержат имена или другие категориальные значения.

In [71]:
five_up = (a > 5) | (a == 4)
five_up

array([[False, False, False,  True],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [72]:
a[five_up]

array([ 4,  6,  7,  8,  9, 10, 11, 12])

Вы можете использовать np.nonzero()для печати индексы элементов, которые, например, меньше 5:

In [73]:
b = np.nonzero(a < 5)
b

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))

Метод np.where() возвращает индексы элементов массива, для которых выполнено условие, передающееся в аргументе (внимание! возвращается кортеж из двух элементов, индексы лежат в первом):

In [74]:
a = np.array([1 , 2, 3, 4, 5, 6, 7, 8])
np.where(a < 5)[0]

array([0, 1, 2, 3])

В этом примере был возвращен кортеж массивов: по одному для каждого измерения. Первый массив представляет индексы строк, в которых находятся эти значения, а второй массив представляет индексы столбцов, в которых находятся эти значения.

Если вы хотите сгенерировать список координат, в которых существуют элементы, вы можете сжать массивы, перебрать список координат и распечатать их. Например:

In [75]:
list_of_coordinates= list(zip(b[0], b[1]))

for coord in list_of_coordinates:
    print(coord)

(0, 0)
(0, 1)
(0, 2)
(0, 3)


### Математическая обработка массивов

Допустим, создали вы два массива, один называется «данные», а другой - «единицы». Тогда их можно складывать, вычитать, умножать (сейчас говорим про поэлементные операции)

In [76]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)
data + ones

array([2, 3])

In [77]:
data - ones

array([0, 1])

In [78]:
data * data

array([1, 4])

In [79]:
data / data

array([1., 1.])

Можно найти сумму всех элементов массива с помощью sum() (работает для массивов с любым количеством размерностей). 

In [80]:
a = np.array([1, 2, 3, 4])

a.sum()

10

Можно найти суммы элементов в каждом из столбцов (или в каждой из строк).

In [81]:
b = np.array([[1, 1], [2, 2]])

In [82]:
b.sum(axis=0)

array([3, 3])

In [83]:
b.sum(axis=1)

array([2, 4])

В некоторых случаях вам может понадобиться выполнить операцию между массивом и одним числом (также называемую операцией между вектором и скаляром) или между массивами двух разных размеров.

In [84]:
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

NumPy понимает, что умножение должно происходить с каждой ячейкой. Размеры вашего массива должны быть совместимы, например, когда размеры обоих массивов равны или когда один из них равен 1. Если размеры не совместимы, вы получите ValueError.

### Полезные операции с массивами 

NumPy также выполняет функции агрегирования. В дополнение к min, max, sum, вы можете легко запустит mean, чтобы получить среднее значение, prod, получить результат умножения элементов, std, чтоб получить стандартное отклонение и многое другое.

In [85]:
data = np.array([1, 2, 3])

In [86]:
data.max()

3

In [87]:
data.min()

1

In [88]:
data.sum()

6

In [89]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

Очень часто хочется собирать данные по ряду или столбцу. По умолчанию каждая функция агрегации NumPy возвращает агрегат всего массива. Чтобы найти сумму или минимум элементов в вашем массиве, запустите:

Любую из функций агрегирования можно применять по строкам или по столбцам. Например, вы можете найти минимальное значение в каждом столбце, указав axis=0.

In [92]:
# минимальное по столбцам
a.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [93]:
# стандартное отклонение по столбцам
a.std(axis=0)

array([0.1794018 , 0.33973673, 0.05524104, 0.00759016])

In [94]:
# среднее по строкам
a.mean(axis=1)

array([0.37958214, 0.38858639, 0.44672607])

### Генерация случайных чисел

Использование генерации случайных чисел является важной частью конфигурации и оценки многих алгоритмов численного и машинного обучения. Независимо от того, нужна ли вам случайная инициализация весов в искусственной нейронной сети, разделение данных на случайные наборы или случайное перемешивание набора данных, очень важно иметь возможность генерировать случайные числа (фактически, повторяемые псевдослучайные числа).

Я рекомендую использовать модуль np.random для генерации случайных чисел. О необходимых методах можно почитать [тут](https://numpy.org/doc/1.16/reference/routines.random.html). Например, получить случайное число от 0 до 10 можно так:

In [155]:
np.random.randint(10)

2

Можно генерировать целые матрицы случайных чисел:


In [156]:
np.random.random((2,3))

array([[0.57638823, 0.76517418, 0.66952793],
       [0.51657338, 0.63404864, 0.69485803]])

### Уникальные значения

Уникальные элементы в массиве ищутся с помощью np.unique.
Например, для такого эррея:

In [157]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
unique_values = np.unique(a)
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


Флаг return_index в аргументе np.unique() поможет получить индексы уникальных значений (самого первого из каждого уникального) в массиве NumPy.

In [116]:
unique_values, indices_list = np.unique(a, return_index=True)
print(indices_list)

[ 0  2  3  4  5  6  7 12 13 14]


Флаг return_counts в аргументе np.unique() поможет получить частоту уникальных значений в массиве NumPy.

In [117]:
unique_values, occurrence_count = np.unique(a, return_counts=True)
print(occurrence_count)

[3 2 2 2 1 1 1 1 1 1]


Все работает и с массивами больших размеров.

In [118]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])

In [119]:
unique_values = np.unique(a_2d)
print(unique_values)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


### Транспонирование и изменение формы матрицы

Для транспонирования (отражения значений относительно диагонали) матрицы можно юзать методы np.transpose() (numpy.ndarray.T) или

Вы также можете использовать .transpose для реверса или изменения осей массива в соответствии с указанными вами значениями.

In [167]:
arr = np.arange(6).reshape((2, 3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [168]:
arr.transpose()
# или
np.transpose(arr)

array([[0, 3],
       [1, 4],
       [2, 5]])

In [166]:
# еще проще
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

### Линейная алгебра

Здесь может быть много непонятных слов - не пугаемся, большинство из этого нам все равно не пригодится. Если кому то будет интересно поподробнее узнать о свойствах/разложениях матриц - подходите и спрашивайте (либо пишите в тг/дискорд).

Возведение в степень:

linalg.matrix_power(M, n) - возводит матрицу в степень n.

Разложения:
* linalg.cholesky(a) - разложение Холецкого.

* linalg.qr(a[, mode]) - QR разложение.

* linalg.svd(a[, full_matrices, compute_uv]) - сингулярное разложение.

Некоторые характеристики матриц:

* linalg.eig(a) - собственные значения и собственные векторы.

* linalg.norm(x[, ord, axis]) - норма вектора или оператора.

* linalg.cond(x[, p]) - число обусловленности.

* linalg.det(a) - определитель.

* linalg.slogdet(a) - знак и логарифм определителя (для избежания переполнения, если сам определитель очень маленький).

Системы уравнений:

* linalg.solve(a, b) - решает систему линейных уравнений Ax = b.

* linalg.tensorsolve(a, b[, axes]) - решает тензорную систему линейных уравнений Ax = b.

* linalg.lstsq(a, b[, rcond]) - метод наименьших квадратов.

* linalg.inv(a) - обратная матрица.

In [133]:
# часто встречающиеся операции
a = np.arange(9).reshape((3,3))

In [134]:
b = np.arange(9)[::-1].reshape((3,3))

In [135]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [136]:
b

array([[8, 7, 6],
       [5, 4, 3],
       [2, 1, 0]])

In [137]:
# матричное перемножение
a @ b

array([[ 9,  6,  3],
       [54, 42, 30],
       [99, 78, 57]])

In [138]:
# матрично-векторные операции
a @ b[0]

array([ 19,  82, 145])

Аналогичный функционал есть и у функции np.dot

In [139]:
# матричное перемножение
np.dot(a, b)

array([[ 9,  6,  3],
       [54, 42, 30],
       [99, 78, 57]])

In [140]:
# матрично-векторные операции
np.dot(a, b[0])

array([ 19,  82, 145])

In [141]:
# скалярное произведение
np.dot(a[0], b[0])

19

In [142]:
a = np.random.randint(10, size = (6, 6))
a

array([[5, 6, 7, 9, 2, 9],
       [3, 4, 1, 8, 8, 9],
       [8, 5, 6, 0, 4, 5],
       [9, 8, 2, 5, 1, 0],
       [1, 8, 1, 6, 5, 2],
       [5, 1, 5, 1, 2, 0]])

In [143]:
np.linalg.inv(a)

array([[-0.04057547,  0.06313328,  0.00682645,  0.11127566, -0.11857625,
         0.01519226],
       [ 0.01298389, -0.08807482,  0.08841907,  0.00361133,  0.11686152,
        -0.1314822 ],
       [ 0.06887503, -0.08651598,  0.00329956, -0.09940244,  0.07113536,
         0.14245259],
       [ 0.04462198,  0.04598597, -0.15685892,  0.04442712, -0.01558846,
         0.10190959],
       [-0.09955183,  0.07950117,  0.00890491, -0.05370226,  0.06796571,
         0.1206742 ],
       [ 0.04892829,  0.02727981,  0.08957521, -0.01940764, -0.06687451,
        -0.16030787]])

In [144]:
a @ np.linalg.inv(a)

array([[ 1.00000000e+00, -6.24500451e-17,  1.11022302e-16,
         2.77555756e-17, -1.66533454e-16, -5.55111512e-17],
       [ 2.28983499e-16,  1.00000000e+00,  0.00000000e+00,
         5.55111512e-17, -1.66533454e-16, -2.77555756e-16],
       [ 6.24500451e-17,  1.31838984e-16,  1.00000000e+00,
         1.11022302e-16, -2.77555756e-16, -1.66533454e-16],
       [ 1.38777878e-17,  5.55111512e-17,  6.59194921e-17,
         1.00000000e+00, -1.11022302e-16, -1.38777878e-17],
       [ 0.00000000e+00, -1.52655666e-16, -5.55111512e-17,
         1.38777878e-17,  1.00000000e+00, -5.55111512e-17],
       [-2.77555756e-17,  5.55111512e-17,  7.63278329e-17,
         8.32667268e-17, -1.66533454e-16,  1.00000000e+00]])

# Задачки (если вы все прочитали)

1. На вход подается целое четное число a. Реализуйте код, создающий numpy массив из значений [0 .. a) с помощью функционала numpy. Полученный массив преобразуйте в массив из 2 столбцов (к форме (a/2, 2)). К полученной последовательности добавьте слева вектор столбец из единиц. Отобразите на экран.

  Sample Input:\
  6

  Sample Output:

  [[1. 0. 1.]\
  [1. 2. 3.]\
  [1. 4. 5.]]

In [144]:
a = int(input())

transformed = 42 ## делаем чета

2. На вход подается numpy массив a и целое b. Возвращайте numpy массив, состоящий из индексов всех вхождений числа b в массив a.

  Sample Input:\
  2, 3 2 1 0

  Sample Output:\
  [1]

In [144]:
b, a = input().split(',')
b = int(b)
a = np.array([int(e) for e in a.split()])

indexes = 42 ## опять чета делаем

3. Написать функцию для подсчёта произведения ненулевых элементов на диагонали прямоугольной матрицы.
Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответом является 3. Если ненулевых элементов нет, функция должна возвращать None.

In [ ]:
X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]])
def nonzero_product(X):
    return 42 ## пишем тут

4. Далее потренеруемся в нормализации - штуке, которая часто используется в машинном обучении чтобы сделать данные однородными.
Напиишите функцию, которая получает на вход матрицу и масштабирует каждый её столбец, а именно вычитает из столбца его среднее значение и делит столбец на стандартное отклонение. Для тестирования можно сгенерировать с помощью метода numpy.random.randint случайную матрицу и проверить на ней работу метода.  Убедитесь, что в функции не будет происходить деления на ноль.

In [175]:
np.random.seed(42) ## фиксируем сид для генератора случайных чисел 
                   ## чтобы они выдавались одинаковые при разных запусках

mat = np.random.randint(0, 10, (2,3))
print(mat)

fixed_mat = np.full((2,3), 42) ## нормализуем тут

[[6 3 7]
 [4 6 9]]
